seed: 42

data:
  h5_path: "./data/gaussians10000_M2560.h5"
  n_gaussians: 10
  M: 2560  # Output resolution
  x_min: -1.0
  x_max: 1.0
  use_subset: true
  samples:
    train: 1000
    val: 100
    test: 100

training:
  batch_size: 128
  epochs: 200
  lr: 5e-4
  weight_decay: 1e-3
  num_workers: 4 # Parallel data loading
  accelerator: "auto" # Auto-selects GPU/MPS/CPU

model:
  type: "DeepONet" # Options: "FFNN", "ResFFNN", "DeepONet"
  hidden_dim: 512
  latent_dim: 256
  num_blocks: 3  # For ResFFNN